version: '3'
services:
    mongo:
        build:
            context: .
            dockerfile: ./compose/mongodb/Dockerfile
        image: improved_spoon_mongo
        volumes:
            - ./mongo-data:/data/db
        ports:
            - "27017-27019:27017-27019"
        environment:
            - MONGO_INITDB_DATABASE=spoon
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_PASSWORD=1qazxsw@
